φ(゜▽゜*)♪ === 2021-12-08 20:04:52 FILE_PATH=(D:/pythonProject/UItestProject/TestApp/RunTest/testcaseRun/testcaserun.py) FUNC-(<module>) <ERRO> LINE-26 *MSG==×('访问url', '运行失败') ===
φ(゜▽゜*)♪ === 2021-12-08 20:04:53 FILE_PATH=(D:/pythonProject/UItestProject/TestApp/RunTest/testcaseRun/testcaserun.py) FUNC-(<module>) <ERRO> LINE-26 *MSG==×('输入', '运行失败') ===
φ(゜▽゜*)♪ === 2021-12-08 20:04:53 FILE_PATH=(D:/pythonProject/UItestProject/TestApp/RunTest/testcaseRun/testcaserun.py) FUNC-(<module>) <ERRO> LINE-26 *MSG==×('点击', '运行失败') ===
φ(゜▽゜*)♪ === 2021-12-08 20:04:53 FILE_PATH=(D:\pythonProject\UItestProject\TestApp\RunTest\basefile\base.py) FUNC-(wait) <ERRO> LINE-53 *MSG==×('等待失败', '\n', TypeError('an integer is required (got type str)')) ===
φ(゜▽゜*)♪ === 2021-12-08 20:04:53 FILE_PATH=(D:/pythonProject/UItestProject/TestApp/RunTest/testcaseRun/testcaserun.py) FUNC-(<module>) <ERRO> LINE-26 *MSG==×('等待3秒', '运行失败') ===
φ(゜▽゜*)♪ === 2021-12-08 20:25:37 FILE_PATH=(D:\pythonProject\UItestProject\TestApp\RunTest\basefile\base.py) FUNC-(wait) <ERRO> LINE-53 *MSG==×('等待失败', '\n', TypeError('an integer is required (got type str)')) ===
φ(゜▽゜*)♪ === 2021-12-08 20:34:24 FILE_PATH=(D:\pythonProject\UItestProject\TestApp\RunTest\basefile\base.py) FUNC-(input) <ERRO> LINE-45 *MSG==×('输入元素', '虚竹修改', '失败', '\n', MaxRetryError("HTTPConnectionPool(host='localhost', port=60843): Max retries exceeded with url: /session/0880eade014110a932f7840018ce7b37/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000173424E62E0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))")) ===
φ(゜▽゜*)♪ === 2021-12-08 20:36:04 FILE_PATH=(D:\pythonProject\UItestProject\TestApp\RunTest\basefile\base.py) FUNC-(input) <ERRO> LINE-45 *MSG==×('输入元素', '虚竹修改', '失败', '\n', MaxRetryError("HTTPConnectionPool(host='localhost', port=60983): Max retries exceeded with url: /session/65694a120ff5b1f2cb554b6c6c276a6b/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000029EB9CB62E0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))")) ===
φ(゜▽゜*)♪ === 2021-12-08 20:36:37 FILE_PATH=(D:\pythonProject\UItestProject\TestApp\RunTest\basefile\base.py) FUNC-(click) <ERRO> LINE-37 *MSG==×('进行点击事件失败', '\n', MaxRetryError("HTTPConnectionPool(host='localhost', port=60983): Max retries exceeded with url: /session/65694a120ff5b1f2cb554b6c6c276a6b/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000029EB9CB6E80>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))")) ===
φ(゜▽゜*)♪ === 2021-12-08 20:37:19 FILE_PATH=(D:\pythonProject\UItestProject\TestApp\RunTest\basefile\base.py) FUNC-(input) <ERRO> LINE-45 *MSG==×('输入元素', '虚竹修改', '失败', '\n', MaxRetryError("HTTPConnectionPool(host='localhost', port=61375): Max retries exceeded with url: /session/bbdfa203d6cfc1be538e871cf9225c0d/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002989B0D83A0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))")) ===
φ(゜▽゜*)♪ === 2021-12-08 20:40:46 FILE_PATH=(D:/pythonProject/UItestProject/TestApp/RunTest/testcaseRun/testcaserun.py) FUNC-(<module>) <ERRO> LINE-30 *MSG==×('程序运行出错，请检查输入的数据',) ===
φ(゜▽゜*)♪ === 2021-12-08 20:42:45 FILE_PATH=(D:/pythonProject/UItestProject/TestApp/RunTest/testcaseRun/testcaserun.py) FUNC-(<module>) <ERRO> LINE-31 *MSG==×('程序运行出错，请检查输入的数据',) ===
φ(゜▽゜*)♪ === 2021-12-15 14:58:50 FILE_PATH=(D:\pythonProject\UItestProject\TestApp\RunTest\testcaseRun\testcaserun.py) FUNC-(<module>) <ERRO> LINE-43 *MSG==×('程序运行出错，请检查输入的数据', TypeError("input() got an unexpected keyword argument 'time_'")) ===
φ(゜▽゜*)♪ === 2021-12-15 15:11:15 FILE_PATH=(D:\pythonProject\UItestProject\TestApp\RunTest\testcaseRun\testcaserun.py) FUNC-(<module>) <ERRO> LINE-43 *MSG==×('程序运行出错，请检查输入的数据', TypeError("input() got an unexpected keyword argument 'time_'")) ===
φ(゜▽゜*)♪ === 2021-12-15 15:14:07 FILE_PATH=(D:\pythonProject\UItestProject\TestApp\RunTest\testcaseRun\testcaserun.py) FUNC-(<module>) <ERRO> LINE-43 *MSG==×('程序运行出错，请检查输入的数据', TypeError("input() got an unexpected keyword argument 'time_'")) ===
φ(゜▽゜*)♪ === 2021-12-15 15:16:10 FILE_PATH=(D:\pythonProject\UItestProject\TestApp\RunTest\testcaseRun\testcaserun.py) FUNC-(<module>) <ERRO> LINE-43 *MSG==×('程序运行出错，请检查输入的数据', NameError("name 'wb' is not defined")) ===
φ(゜▽゜*)♪ === 2021-12-15 15:16:10 FILE_PATH=(D:\pythonProject\UItestProject\TestApp\RunTest\testcaseRun\testcaserun.py) FUNC-(<module>) <ERRO> LINE-43 *MSG==×('程序运行出错，请检查输入的数据', NameError("name 'wb' is not defined")) ===
φ(゜▽゜*)♪ === 2021-12-15 15:18:16 FILE_PATH=(D:\pythonProject\UItestProject\TestApp\RunTest\testcaseRun\testcaserun.py) FUNC-(<module>) <ERRO> LINE-45 *MSG==×('程序运行出错，请检查输入的数据', TypeError("input() got an unexpected keyword argument 'time_'")) ===
φ(゜▽゜*)♪ === 2021-12-15 15:38:01 FILE_PATH=(D:\pythonProject\UItestProject\TestApp\RunTest\testcaseRun\testcaserun.py) FUNC-(runTest) <ERRO> LINE-41 *MSG==×('程序运行出错，请检查输入的数据', TypeError("input() got an unexpected keyword argument 'time_'")) ===
φ(゜▽゜*)♪ === 2021-12-15 22:07:02 FILE_PATH=(D:\pythonProject\UItestProject\TestApp\RunTest\testcaseRun\testcaserun.py) FUNC-(runTest) <ERRO> LINE-44 *MSG==×('程序运行出错，请检查输入的数据', FileNotFoundError(2, 'No such file or directory')) ===
φ(゜▽゜*)♪ === 2021-12-15 22:08:42 FILE_PATH=(D:\pythonProject\UItestProject\TestApp\RunTest\testcaseRun\testcaserun.py) FUNC-(runTest) <ERRO> LINE-44 *MSG==×('程序运行出错，请检查输入的数据', FileNotFoundError(2, 'No such file or directory')) ===
φ(゜▽゜*)♪ === 2021-12-15 22:16:10 FILE_PATH=(D:\pythonProject\UItestProject\TestApp\RunTest\testcaseRun\testcaserun.py) FUNC-(runTest) <ERRO> LINE-49 *MSG==×('程序运行出错，请检查输入的数据', FileNotFoundError(2, 'No such file or directory')) ===
φ(゜▽゜*)♪ === 2021-12-15 22:19:00 FILE_PATH=(D:\pythonProject\UItestProject\TestApp\RunTest\testcaseRun\testcaserun.py) FUNC-(runTest) <ERRO> LINE-50 *MSG==×('程序运行出错，请检查输入的数据', FileNotFoundError(2, 'No such file or directory')) ===
φ(゜▽゜*)♪ === 2021-12-19 17:29:06 FILE_PATH=(D:\pythonProject\UItestProject\TestApp\RunTest\testcaseRun\testcaserun.py) FUNC-(runTest) <ERRO> LINE-67 *MSG==×('程序运行出错，请检查输入的数据', TypeError("unsupported operand type(s) for +: 'WindowsPath' and 'str'")) ===
φ(゜▽゜*)♪ === 2021-12-19 17:30:34 FILE_PATH=(D:\pythonProject\UItestProject\TestApp\RunTest\testcaseRun\testcaserun.py) FUNC-(runTest) <ERRO> LINE-67 *MSG==×('程序运行出错，请检查输入的数据', TypeError("unsupported operand type(s) for +: 'WindowsPath' and 'str'")) ===
φ(゜▽゜*)♪ === 2021-12-19 19:15:53 FILE_PATH=(D:\pythonProject\UItestProject\TestApp\RunTest\testcaseRun\testcaserun.py) FUNC-(runTest) <ERRO> LINE-69 *MSG==×('程序运行出错，请检查输入的数据', TypeError("unsupported operand type(s) for +: 'WindowsPath' and 'str'")) ===
φ(゜▽゜*)♪ === 2021-12-20 21:19:34 FILE_PATH=(D:\pythonProject\UItestProject\TestApp\RunTest\testcaseRun\testcaserun.py) FUNC-(runTest) <ERRO> LINE-80 *MSG==×('程序运行出错，请检查输入的数据', TypeError("unsupported operand type(s) for +: 'int' and 'str'")) ===
φ(゜▽゜*)♪ === 2021-12-20 21:21:20 FILE_PATH=(D:\pythonProject\UItestProject\TestApp\RunTest\testcaseRun\testcaserun.py) FUNC-(runTest) <ERRO> LINE-80 *MSG==×('程序运行出错，请检查输入的数据', AttributeError("'WindowsPath' object has no attribute 'rstrip'")) ===
φ(゜▽゜*)♪ === 2021-12-21 21:27:12 FILE_PATH=(D:\pythonProject\UItestProject\TestApp\RunTest\testcaseRun\testcaserun.py) FUNC-(runTest) <ERRO> LINE-86 *MSG==×('程序运行出错，请检查输入的数据', NoReverseMatch("Reverse for 'report' with keyword arguments '{'kwargs': {'filename': 'testzz.xlsx'}}' not found. 1 pattern(s) tried: ['report/(?P<filename>[^/]+)$']")) ===
φ(゜▽゜*)♪ === 2021-12-24 15:53:22 FILE_PATH=(D:\pythonProject\UItestProject\TestApp\RunTest\testcaseRun\testcaserun.py) FUNC-(runTest) <ERRO> LINE-81 *MSG==×('程序运行出错，请检查输入的数据', TypeError("unsupported operand type(s) for +: 'int' and 'str'")) ===
φ(゜▽゜*)♪ === 2021-12-24 15:56:54 FILE_PATH=(D:\pythonProject\UItestProject\TestApp\RunTest\testcaseRun\testcaserun.py) FUNC-(runTest) <ERRO> LINE-81 *MSG==×('程序运行出错，请检查输入的数据', IntegrityError(1048, "Column 'modelName' cannot be null")) ===
φ(゜▽゜*)♪ === 2021-12-24 20:16:39 FILE_PATH=(D:\pythonProject\UItestProject\TestApp\RunTest\basefile\base.py) FUNC-(click) <ERRO> LINE-48 *MSG==×('进行点击事件失败', '\n', NoSuchElementException('no such element: Unable to locate element: {"method":"css selector","selector":"[id="su1"]"}\n  (Session info: chrome=96.0.4664.110)', None, ['Backtrace:', '\tOrdinal0 [0x004E6903+2517251]', '\tOrdinal0 [0x0047F8E1+2095329]', '\tOrdinal0 [0x00382848+1058888]', '\tOrdinal0 [0x003AD448+1233992]', '\tOrdinal0 [0x003AD63B+1234491]', '\tOrdinal0 [0x003D7812+1406994]', '\tOrdinal0 [0x003C650A+1336586]', '\tOrdinal0 [0x003D5BBF+1399743]', '\tOrdinal0 [0x003C639B+1336219]', '\tOrdinal0 [0x003A27A7+1189799]', '\tOrdinal0 [0x003A3609+1193481]', '\tGetHandleVerifier [0x00675904+1577972]', '\tGetHandleVerifier [0x00720B97+2279047]', '\tGetHandleVerifier [0x00576D09+534521]', '\tGetHandleVerifier [0x00575DB9+530601]', '\tOrdinal0 [0x00484FF9+2117625]', '\tOrdinal0 [0x004898A8+2136232]', '\tOrdinal0 [0x004899E2+2136546]', '\tOrdinal0 [0x00493541+2176321]', '\tBaseThreadInitThunk [0x767DFA29+25]', '\tRtlGetAppContainerNamedObjectPath [0x77BF7A9E+286]', '\tRtlGetAppContainerNamedObjectPath [0x77BF7A6E+238]', ''])) ===
